In [23]:
import torch
H, W = 3, 4
torch.linspace(0, H - 1, H)

tensor([0., 1., 2.])

In [45]:
i, j = torch.meshgrid(torch.linspace(0, W - 1, W), torch.linspace(0, H - 1, H), indexing = 'ij')

In [46]:
i

tensor([[0., 0., 0.],
        [1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.]])

In [35]:
c2w = torch.zeros((3, 4, 4))
prefix = c2w.shape[:-2]
i = i.reshape([*[1]*len(prefix), H * W])
i

tensor([[0., 1., 2., 3., 0., 1., 2., 3., 0., 1., 2., 3.]])

In [18]:
c2w = torch.zeros((3, 4, 4))
c2w.shape[:-2]

torch.Size([3])

In [47]:
N_imgs = 2
i, j = torch.meshgrid(torch.linspace(0, W-1, W), torch.linspace(0, H-1, H), indexing='xy')
i = i.reshape((-1, H * W)).expand(N_imgs, H * W)
j = j.reshape((-1, H * W)).expand(N_imgs, H * W)

In [48]:
i.shape

torch.Size([2, 12])

In [55]:
torch.gather(i, -1, torch.LongTensor([[0, 1, 3], [2, 3, 4]]))

tensor([[0., 1., 3.],
        [2., 3., 0.]])

In [53]:
i[0]

tensor([0., 1., 2., 3., 0., 1., 2., 3., 0., 1., 2., 3.])

In [2]:
import torch
torch.rand(1, 1000, 1, 2).shape

torch.Size([1, 1000, 1, 2])

In [4]:
torch.rand(1, 5)

tensor([[0.1779, 0.5358, 0.3045, 0.0386, 0.3415]])

In [16]:
import torch.nn.functional as F
max_range = 0.7
min_range = -0.7
grid = torch.rand(10, 100, 10, 2)
ref_feature = torch.randn((10, 64, 480, 640))
feature = F.grid_sample(ref_feature, grid, mode='bilinear', align_corners=True, padding_mode='border')

In [17]:
feature.shape

torch.Size([10, 64, 100, 10])

In [11]:
grid.shape

torch.Size([10, 10, 1, 2])

In [18]:
torch.arange(0, 5, 1)

tensor([0, 1, 2, 3, 4])